/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    MyButton: typeof import('./src/components/MyButton/MyButton.vue')['default']
    MyConfirm: typeof import('./src/components/MyConfirm/MyConfirm.vue')['default']
    MyInput: typeof import('./src/components/MyInput/MyInput.vue')['default']
    MySelect: typeof import('./src/components/MySelect/MySelect.vue')['default']
    MyShowInfo: typeof import('./src/components/MyShowInfo/MyShowInfo.vue')['default']
    MyShowItem: typeof import('./src/components/MyShowItem/MyShowItem.vue')['default']
    MyTab: typeof import('./src/components/MyTab/MyTab.vue')['default']
    MyTable: typeof import('./src/components/MyTable/MyTable.vue')['default']
    NoData: typeof import('./src/components/NoData/NoData.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdateComponent: typeof import('./src/components/UpdateComponent/UpdateComponent.vue')['default']
    VanBadge: typeof import('vant/es')['Badge']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanField: typeof import('vant/es')['Field']
    VanFloatingPanel: typeof import('vant/es')['FloatingPanel']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPopover: typeof import('vant/es')['Popover']
    VanPopup: typeof import('vant/es')['Popup']
    VanProgress: typeof import('vant/es')['Progress']
    VanSlider: typeof import('vant/es')['Slider']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
